version: '3.4'

services:
  nfs-server:
    image: lnls/nfs-server
    ports:
      - "111:111/tcp"
      - "111:111/udp"
      - "2049:2049/tcp"
      - "2049:2049/udp"
      - "32765-32769:32765-32769/tcp"
      - "32765-32769:32765-32769/udp"
    depends_on:
      - debian-rootfs
      - debian-homefs
    container_name: nfs-server
    command: ["/exports/rootfs,*,ro,async",
                "/exports/home/dell-r230-server-1,*,ro,async",
                "/exports/home/dell-r230-server-2,*,ro,async",
                "/exports/autosave/dell-r230-server-1,*,rw,async",
                "/exports/autosave/dell-r230-server-2,*,rw,async"
    ]
    volumes:
      - type: volume
        source: debian-rootfs-volume
        target: /exports/rootfs
        volume:
          read_only: true
      - type: volume
        source: debian-homefs-volume
        target: /exports/home
        volume:
          read_only: true
      - type: volume
        source: autosave-volume
        target: /exports/autosave
    privileged: true

  debian-rootfs:
    image: lnls/debian-rootfs
    container_name: debian-rootfs
    volumes:
      - type: volume
        source: debian-rootfs-volume
        target: /rootfs
        volume:
          read_only: true

  debian-homefs:
    image: lnls/debian-homefs
    container_name: debian-homefs
    volumes:
      - type: volume
        source: debian-homefs-volume
        target: /homefs
        volume:
          read_only: true

volumes:
  debian-rootfs-volume:
  debian-homefs-volume:
  autosave-volume:
