version: '3.4'

services:
  nfs-server:
    image: lnlsdig/nfs-server
    ports:
      - "111:111/udp"
      - "2049:2049/tcp"
      - "32765-32769:32765-32769/tcp"
      - "32765-32769:32765-32769/udp"
    container_name: nfs-server
    depends_on:
      - debian-nfs-image
    command: ["/"]
    volumes:
      - type: volume
        source: debian-nfs-image-volume
        target: /nfsroot
        volume:
          read_only: true
    network_mode: "host"
    privileged: true

  debian-nfs-image:
    image: lnlsdig/debian-nfs-image
    container_name: debian-nfs-image
    volumes:
      - type: volume
        source: debian-nfs-image-volume
        target: /nfsroot
        volume:
          read_only: true

volumes:
  debian-nfs-image-volume:
