version: '3.4'

services:
  nfs-server:
    restart: always
    image: lnls/nfs-server
    ports:
      - "111:111/tcp"
      - "111:111/udp"
      - "2049:2049/tcp"
      - "2049:2049/udp"
      - "32765-32769:32765-32769/tcp"
      - "32765-32769:32765-32769/udp"
    depends_on:
      - debian-rootfs
      - debian-homefs
    container_name: nfs-server
    command: ["/exports/rootfs,*,ro,async",
                "/exports/home/IA-20RaDiag01-CO-IOCSrv-1,*,ro,async",
                "/exports/home/IA-20RaDiag01-CO-IOCSrv-2,*,ro,async",
                "/exports/home/IA-20RaDiag02-CO-IOCSrv-1,*,ro,async",
                "/exports/home/IA-20RaDiag02-CO-IOCSrv-2,*,ro,async",
                "/exports/home/IA-14RaDiag03-CO-IOCSrv,*,ro,async",
                "/exports/home/IA-18RaDiag04-CO-IOCSrv,*,ro,async",
                "/exports/home/IA-16RaBbB-CO-IOCSrv,*,ro,async",
                "/exports/home/CA-RaCtrl-CO-IOCSrv-2,*,ro,async",
                "/exports/home/dell-r230-server-9,*,ro,async",
                "/exports/home/dell-r230-server-10,*,ro,async",
                "/exports/autosave/IA-20RaDiag01-CO-IOCSrv-1,*,rw,async",
                "/exports/autosave/IA-20RaDiag01-CO-IOCSrv-2,*,rw,async",
                "/exports/autosave/IA-20RaDiag02-CO-IOCSrv-1,*,rw,async",
                "/exports/autosave/IA-20RaDiag02-CO-IOCSrv-2,*,rw,async",
                "/exports/autosave/IA-14RaDiag03-CO-IOCSrv,*,rw,async",
                "/exports/autosave/IA-18RaDiag04-CO-IOCSrv,*,rw,async",
                "/exports/autosave/IA-16RaBbB-CO-IOCSrv,*,rw,async",
                "/exports/autosave/CA-RaCtrl-CO-IOCSrv-2,*,rw,async",
                "/exports/autosave/dell-r230-server-9,*,rw,async",
                "/exports/autosave/dell-r230-server-10,*,rw,async"
    ]
    volumes:
      - type: volume
        source: debian-rootfs-volume
        target: /exports/rootfs
        volume:
          read_only: true
      - type: volume
        source: debian-homefs-volume
        target: /exports/home
        volume:
          read_only: true
      - type: volume
        source: autosave-volume
        target: /exports/autosave
    privileged: true

  debian-rootfs:
    image: lnls/debian-rootfs:9.7-kernel-4.9.0-8-20190201-1
    container_name: debian-rootfs
    volumes:
      - type: volume
        source: debian-rootfs-volume
        target: /rootfs
        volume:
          read_only: true

  debian-homefs:
    image: lnls/debian-homefs
    container_name: debian-homefs
    volumes:
      - type: volume
        source: debian-homefs-volume
        target: /homefs
        volume:
          read_only: true

volumes:
  debian-rootfs-volume:
  debian-homefs-volume:
  autosave-volume:
