version: '3.4'

services:
  nfs-server:
    image: lnls/nfs-server
    ports:
      - "111:111/tcp"
      - "111:111/udp"
      - "2049:2049/tcp"
      - "2049:2049/udp"
      - "32765-32769:32765-32769/tcp"
      - "32765-32769:32765-32769/udp"
    container_name: nfs-server
    command: ["/exports/rootfs,*",
                "/exports/home/dell-r230-server-1,*",
                "/exports/home/dell-r230-server-2,*"
    ]
    volumes:
      - type: bind
        source: ./debian-rootfs/exports/rootfs
        target: /exports/rootfs
        volume:
          read_only: true
      - type: bind
        source: ./debian-rootfs/exports/home
        target: /exports/home
        volume:
          read_only: true
    privileged: true
